site_name: DataTorrent Documentation
google_analytics: ['UA-44586211-2', 'docs.datatorrent.com']
site_favicon: favicon.ico
theme: readthedocs
pages:
- DataTorrent RTS: index.md
- Demos:
    - Running Apps: demos.md
- Sandbox: sandbox.md
- Development:
    - Creating Applications: create.md
    - "Beginner's Guide": beginner.md
    - Videos: demo_videos.md
    - Tutorials:
        - Top N Words:
            - Introduction: tutorials/topnwords.md
            - Development Environment: tutorials/topnwords-c1.md
            - Building in Java: tutorials/topnwords-c2.md
            - Building with dtAssemble: tutorials/topnwords-c3.md
            - Monitoring with dtManage: tutorials/topnwords-c4.md
            - Visualizing with dtDashboard: tutorials/topnwords-c5.md
            - Advanced Features: tutorials/topnwords-c7.md
            - Appendix: tutorials/topnwords-c6.md
        - Sales Dimensions:
            - Building in Java: tutorials/salesdimensions.md
            - Building with dtAssemble: tutorials/salesdimensions-c2.md
            - Visualizing with dtDashboard: tutorials/salesdimensions-c3.md
            - Monitoring with dtManage: tutorials/salesdimensions-c4.md
    - Apex Development Setup: apex_development_setup.md
    - Generate New Project in IDE: configure_IDE.md
    - Applications: application_development.md
    - Application Packages: application_packages.md
    - Configuration Packages: configuration_packages.md
    - Operators: operator_development.md
    - Library Operators:
        - List of Operators: library_operators.md
        - Block Reader: operators/block_reader.md
        - Deduper: operators/deduper.md
        - Dimension Computation: operators/dimensions_computation.md
        - File Output: operators/file_output.md  
        - File Splitter: operators/file_splitter.md
        - HDHT: operators/hdht.md
        - Kafka Input: operators/kafkaInputOperator.md
        - Snapshot Server: operators/snapshot_server.md
    - App Data Framework: app_data_framework.md
    - REST API: dtgateway_api.md
- App Templates:
    - Database dump to HDFS App: app-templates/database-to-hdfs.md
    - Database to Database Sync App: app-templates/database-to-database-sync.md
    - HDFS Sync App: app-templates/hdfs-sync.md
    - HDFS to HDFS Line Copy App: app-templates/hdfs-line-copy.md
    - HDFS to Kafka Sync App: app-templates/hdfs-to-kafka-sync.md
    - Kafka to Database Sync App: app-templates/kafka-to-database-sync.md
    - Kafka to HDFS Filter App: app-templates/kafka-to-hdfs-filter.md
    - Kafka to HDFS Sync App: app-templates/kafka-to-hdfs-sync.md
    - S3 to HDFS Sync App: app-templates/s3-to-hdfs-sync.md
- Applications:
    - App Data Tracker: app_data_tracker.md
    - dtIngest: dtingest.md
- Platform:
    - RTS: rts.md
    - dtManage: dtmanage.md
    - dtAssemble: dtassemble.md
    - dtDashboard: dtdashboard.md
    - dtGateway: dtgateway.md
    - Alerts: dtgateway_systemalerts.md
    - Apache Apex: apex.md
    - Apache Apex-Malhar: apex_malhar.md
- Deployment and Operations:
    - Installation: installation.md
    - Configuration: configuration.md
    - Security: dtgateway_security.md
    - System Alerts: dtgateway_systemalerts.md
    - Apex CLI: apexcli.md
    - Troubleshooting: troubleshooting.md
- Release Notes: release_notes.md
- Glossary: glossary.md
- Resources: additional_docs.md
